# Generated by Django 5.0.4 on 2024-04-26 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projapp', '0003_alter_produto_estoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='estoque',
        ),
    ]
